server:
  port: 80

spring:
  datasource:
    #数据库类型
    type: com.zaxxer.hikari.HikariDataSource
    #数据库设置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8
    username: root
    password: wangzeyuan202
  data:
    redis:
      #Redis服务器地址
      host: 47.120.15.38
      #端口
      port: 6379
      #使用几号数据库
      database: 0
      # Redis服务器连接密码（默认为空）
      password: 202105
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-wait: -1
          # 连接池中的最大空闲连接 默认 8
          max-idle: 8
          # 连接池中的最小空闲连接 默认 0
          min-idle: 0
      timeout: 3000
  mail:
    host: smtp.qq.com
    username: 2756949672@qq.com
    password: xitbehltlinrdccd
    port: 465
    properties:
      from: 275694962@qq.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory




#MyBatis-Plus配置
mybatis-plus:
  configuration:
    #配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  ##指定mapper文件所在的地址   扫描mapper下的所有xml文件
  mapper-locations: classpath:mapper/**/*.xml
  #设置Mybatis-plus的全局配置
  global-config:
    db-config:
      # 设置实体类所对应的表的统一前缀
      table-prefix:
      #配置mp的主键策略
      id-type:
  #配置类型别名所对应的包
  type-aliases-package: com.wzy.studyprojectbackend.entity.domain
  # 扫描通用枚举的包
  type-enums-package: