server:
  port: 80

spring:
  datasource:
    #数据库类型
    type: com.zaxxer.hikari.HikariDataSource
    #数据库设置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8
    username: root
    password: wangzeyuan202
  data:
    redis:
      host: localhost
      port: 6379

#MyBatis-Plus配置
mybatis-plus:
  configuration:
    #配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  ##指定mapper文件所在的地址   扫描mapper下的所有xml文件
  mapper-locations: classpath:mapper/**/*.xml
  #设置Mybatis-plus的全局配置
  global-config:
    db-config:
      # 设置实体类所对应的表的统一前缀
      table-prefix:
      #配置mp的主键策略
      id-type:
  #配置类型别名所对应的包
  type-aliases-package: com.wzy.studyprojectbackend.entity.domain
  # 扫描通用枚举的包
  type-enums-package: